server {
    listen 80;
    server_name uzenergotaminlash.uz www.uzenergotaminlash.uz;

    # Favicon
    location = /favicon.ico { access_log off; log_not_found off; }

    # Static fayllar
    location /static/ {
        root /var/www/uzenergotaminlash;
    }

    # Media fayllar (yuklangan hujjatlar va rasmlar)
    location /media/ {
        root /var/www/uzenergotaminlash;
    }

    # Gunicorn ga so'rovlarni uzatish
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    # SSL Certbot qo'shilgandan so'ng HTTP -> HTTPS redirects
    # avtomatik ravishda shu faylga yoziladi
}
