# Generated by Django 6.0.7 on 2026-07-08 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='Kompaniya haqida', max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(default='О компании', max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(default='About Company', max_length=200, verbose_name='Title (EN)')),
                ('content_uz', models.TextField(verbose_name='Matn (UZ)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Text (EN)')),
                ('mission_uz', models.TextField(blank=True, verbose_name='Missiya (UZ)')),
                ('mission_ru', models.TextField(blank=True, verbose_name='Миссия (RU)')),
                ('mission_en', models.TextField(blank=True, verbose_name='Mission (EN)')),
                ('vision_uz', models.TextField(blank=True, verbose_name='Vizyon (UZ)')),
                ('vision_ru', models.TextField(blank=True, verbose_name='Видение (RU)')),
                ('vision_en', models.TextField(blank=True, verbose_name='Vision (EN)')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Rasm')),
                ('years_experience', models.PositiveIntegerField(default=10, verbose_name='Tajriba yillari')),
                ('clients_count', models.PositiveIntegerField(default=500, verbose_name='Mijozlar soni')),
                ('projects_count', models.PositiveIntegerField(default=1000, verbose_name='Loyihalar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kompaniya haqida',
                'verbose_name_plural': 'Kompaniya haqida',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (EN)')),
                ('subtitle_uz', models.TextField(verbose_name='Qisqa tavsif (UZ)')),
                ('subtitle_ru', models.TextField(blank=True, verbose_name='Краткое описание (RU)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Short description (EN)')),
                ('btn_catalog_uz', models.CharField(default='Katalog', max_length=100, verbose_name='Katalog tugmasi (UZ)')),
                ('btn_catalog_ru', models.CharField(default='Каталог', max_length=100, verbose_name='Кнопка каталога (RU)')),
                ('btn_catalog_en', models.CharField(default='Catalog', max_length=100, verbose_name='Catalog button (EN)')),
                ('btn_contact_uz', models.CharField(default="Bog'lanish", max_length=100, verbose_name="Bog'lanish tugmasi (UZ)")),
                ('btn_contact_ru', models.CharField(default='Связаться', max_length=100, verbose_name='Кнопка связи (RU)')),
                ('btn_contact_en', models.CharField(default='Contact Us', max_length=100, verbose_name='Contact button (EN)')),
                ('background_image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Fon rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Hero bo'limi",
                'verbose_name_plural': "Hero bo'limi",
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (EN)')),
                ('content_uz', models.TextField(verbose_name='Matn (UZ)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Text (EN)')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Rasm')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL (slug)')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(blank=True, default='bi-lightning-charge', max_length=50, verbose_name='Bootstrap Icon klassi')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(blank=True, max_length=50, verbose_name='Telefon 1')),
                ('phone_2', models.CharField(blank=True, max_length=50, verbose_name='Telefon 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_uz', models.CharField(blank=True, max_length=300, verbose_name='Manzil (UZ)')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='Адрес (RU)')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Address (EN)')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('meta_title_uz', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (UZ)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (RU)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_description_uz', models.TextField(blank=True, verbose_name='Meta Description (UZ)')),
                ('meta_description_ru', models.TextField(blank=True, verbose_name='Meta Description (RU)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_keywords', models.TextField(blank=True, default="uz uzet uzenergo uze energo ta'minlash elektr jihozlari transformator generator", verbose_name='Meta Keywords (SEO)')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('image', models.ImageField(blank=True, upload_to='catalog/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='main.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': "Katalog bo'limi",
                'verbose_name_plural': "Katalog bo'limlari",
                'ordering': ['order'],
            },
        ),
    ]
