# Generated by Django 4.2.30 on 2026-07-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='service',
        ),
    ]
