# Generated by Django 4.2.30 on 2026-07-10 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_catalogitem_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (slug)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Korporativ kategoriya',
                'verbose_name_plural': 'Korporativ kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CorporateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (EN)')),
                ('file', models.FileField(upload_to='corporate_docs/', verbose_name='Fayl (PDF/DOC)')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='Yil (0 = Arxiv)')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Arxivda')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.corporatecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Korporativ hujjat',
                'verbose_name_plural': 'Korporativ hujjatlar',
                'ordering': ['order', '-published_date'],
            },
        ),
    ]
