# Generated by Django 4.2.30 on 2026-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_corporatecategory_corporatedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hamkor nomi')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Logotip (Rasm)')),
                ('link', models.URLField(blank=True, verbose_name='Saytga havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.TextField(blank=True, default="uz uzet uzenergo uze energo ta'minlash energetika katalog mahsulotlar elektr jihozlari transformator generator", verbose_name='Meta Keywords (SEO)'),
        ),
    ]
