# Generated by Django 4.2.30 on 2026-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partner_alter_sitesettings_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Xaritani ulash uchun Iframe kodini shu yerga kiriting', verbose_name='Xarita Iframe (Google/Yandex)'),
        ),
    ]
