# Generated by Django 6.0.7 on 2026-07-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings_map_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_domain',
            field=models.CharField(blank=True, default='', help_text="Misol: https://uzenergotaminlash.uz (oxirida / bo'lmasin). Bo'sh qolsa avtomatik aniqlanadi.", max_length=200, verbose_name='Sayt domeni'),
        ),
    ]
