# Generated by Django 6.0.7 on 2026-07-14 06:53

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesettings_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.FileField(upload_to='partners/', validators=[main.models.validate_svg_or_image], verbose_name='Logotip (Rasm yoki SVG)'),
        ),
    ]
