# Generated by Django 4.2.30 on 2026-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatedocument',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='corporate_docs/', verbose_name='Fayl (EN)'),
        ),
        migrations.AddField(
            model_name='corporatedocument',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='corporate_docs/', verbose_name='Fayl (RU)'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='file',
            field=models.FileField(upload_to='corporate_docs/', verbose_name='Fayl (UZ) (Asosiy)'),
        ),
    ]
