# Generated by Django 4.2.30 on 2026-07-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_corporatedocument_file_en_corporatedocument_file_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatedocument',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='corporatedocument',
            name='file_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_domain',
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='file',
            field=models.FileField(upload_to='corporate_docs/', verbose_name='Fayl (PDF/DOC)'),
        ),
    ]
