# Generated by Django 6.0.7 on 2026-07-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_corporatedocument_file_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='mission_en',
            new_name='asosiy_vazifa_en',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='mission_ru',
            new_name='asosiy_vazifa_ru',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='mission_uz',
            new_name='asosiy_vazifa_uz',
        ),
    ]
