# Generated by Django 6.0.7 on 2026-07-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_mission_en_aboutsection_asosiy_vazifa_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='asosiy_vazifa_en',
            field=models.TextField(blank=True, verbose_name='Asosiy vazifa (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='asosiy_vazifa_ru',
            field=models.TextField(blank=True, verbose_name='Asosiy vazifa (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='asosiy_vazifa_uz',
            field=models.TextField(blank=True, verbose_name='Asosiy vazifa (UZ)'),
        ),
    ]
