# Generated by Django 6.0.7 on 2026-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_aboutsection_asosiy_vazifa_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_title_uz',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#0ea5e9', help_text='Ikkinchi darajali rang (hex)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bg_color',
            field=models.CharField(default='#f8fafc', help_text='Fon rangi — kunduzgi rejim uchun och rang maslahat beriladi (hex)', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#f59e0b', help_text='Asosiy brand rangi (hex)', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#0f172a', help_text='Asosiy matn rangi (hex)', max_length=7, verbose_name='Text Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_secondary_color',
            field=models.CharField(default='#475569', help_text='Ikkinchi darajali matn rangi (hex)', max_length=7, verbose_name='Secondary Text Color'),
        ),
    ]
