# Generated by Django 6.0.7 on 2026-07-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_sitesettings_meta_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bg_card_color',
            field=models.CharField(default='#ffffff', help_text='Karta/blok foni (hex)', max_length=7, verbose_name='Karta foni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bg_section_color',
            field=models.CharField(default='#f1f5f9', help_text="Bo'lim foni (alternativ, hex)", max_length=7, verbose_name="Bo'lim foni"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='rgba(0,0,0,0.1)', help_text='Chegara rangi — rgba yoki hex (masalan: rgba(0,0,0,0.1))', max_length=20, verbose_name='Chegara rangi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_color',
            field=models.CharField(default='#f8fafc', help_text='Sahifa umumiy foni (hex)', max_length=7, verbose_name='Sahifa foni'),
        ),
    ]
