# Generated by Django 6.0.7 on 2026-07-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesettings_bg_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='background_image_light',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Fon rasmi (Kunduzgi rejim)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name="Fon rasmi (Asosiy/Qorong'i)"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#cc0000', help_text='Ikkinchi darajali rang (hex)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_card_color',
            field=models.CharField(default='#f4f4f4', help_text='Karta/blok foni (hex)', max_length=7, verbose_name='Karta foni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_color',
            field=models.CharField(default='#ffffff', help_text='Sahifa umumiy foni (hex)', max_length=7, verbose_name='Sahifa foni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_section_color',
            field=models.CharField(default='#f8f9fa', help_text="Bo'lim foni (alternativ, hex)", max_length=7, verbose_name="Bo'lim foni"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='#e0e0e0', help_text='Chegara rangi — rgba yoki hex (masalan: rgba(0,0,0,0.1))', max_length=20, verbose_name='Chegara rangi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#ff000f', help_text='Asosiy brand rangi (hex)', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#111111', help_text='Asosiy matn rangi (hex)', max_length=7, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_secondary_color',
            field=models.CharField(default='#555555', help_text='Ikkinchi darajali matn rangi (hex)', max_length=7, verbose_name='Secondary Text Color'),
        ),
    ]
