# Generated by Django 6.0.7 on 2026-07-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_herosection_background_image_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='background_video',
            field=models.FileField(blank=True, help_text="Ixtiyoriy. Qisqa MP4/WebM (tavsiya: 3–8 soniya, <3MB). Bo'sh bo'lsa engil canvas animatsiya ishlaydi.", upload_to='hero/videos/', verbose_name="Fon video (Qorong'i)"),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_video_light',
            field=models.FileField(blank=True, help_text="Ixtiyoriy. Kunduzgi rejim uchun. Bo'sh bo'lsa qorong'i video yoki canvas ishlatiladi.", upload_to='hero/videos/', verbose_name='Fon video (Kunduzgi)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Matn (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(default='О компании', max_length=200, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision_ru',
            field=models.TextField(blank=True, verbose_name='Vizyon (RU)'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='corporatecategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_catalog_ru',
            field=models.CharField(default='Каталог', max_length=100, verbose_name='Katalog tugmasi (RU)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_contact_ru',
            field=models.CharField(default='Связаться', max_length=100, verbose_name="Bog'lanish tugmasi (RU)"),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle_ru',
            field=models.TextField(blank=True, verbose_name='Qisqa tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Matn (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#0284c7', help_text='Ikkinchi darajali rang (hex)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (RU)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_card_color',
            field=models.CharField(default='#ffffff', help_text='Karta/blok foni (hex)', max_length=7, verbose_name='Karta foni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_color',
            field=models.CharField(default='#f3f6fa', help_text='Sahifa umumiy foni (hex)', max_length=7, verbose_name='Sahifa foni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_section_color',
            field=models.CharField(default='#e7edf5', help_text="Bo'lim foni (alternativ, hex)", max_length=7, verbose_name="Bo'lim foni"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='rgba(15,35,60,0.1)', help_text='Chegara rangi — rgba yoki hex (masalan: rgba(0,0,0,0.1))', max_length=20, verbose_name='Chegara rangi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#e8910c', help_text='Asosiy brand rangi (hex)', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#0b1220', help_text='Asosiy matn rangi (hex)', max_length=7, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_secondary_color',
            field=models.CharField(default='#3d4f66', help_text='Ikkinchi darajali matn rangi (hex)', max_length=7, verbose_name='Secondary Text Color'),
        ),
    ]
