# Generated by Django 6.0.7 on 2026-07-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_herosection_background_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='rgba(15,35,60,0.1)', help_text='Chegara rangi — rgba yoki hex (masalan: rgba(0,0,0,0.1))', max_length=40, verbose_name='Chegara rangi'),
        ),
    ]
