# Generated by Django 6.0.7 on 2026-07-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_border_color_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title (UZ)'),
        ),
    ]
