# Generated by Django 6.0.7 on 2026-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_restore_meta_title_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_en',
            field=models.CharField(blank=True, default="JSC O'ZENERGOTA'MINLASH", max_length=200, verbose_name='Company name (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_ru',
            field=models.CharField(blank=True, default="АО O'ZENERGOTA'MINLASH", max_length=200, verbose_name='Kompaniya nomi (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_uz',
            field=models.CharField(blank=True, default="O'ZENERGOTA'MINLASH", max_length=200, verbose_name='Kompaniya nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_tagline_uz',
            field=models.CharField(blank=True, default='AKSIYADORLIK JAMIYATI', max_length=200, verbose_name='Tagline (UZ)'),
        ),
    ]
