# Generated by Django 4.2.30 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_company_brand_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='badge_en',
            field=models.CharField(blank=True, default='Solutions for Energy', max_length=120, verbose_name='Hero badge (EN)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='badge_ru',
            field=models.CharField(blank=True, default='Решения для энергетики', max_length=120, verbose_name='Hero badge (RU)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='badge_uz',
            field=models.CharField(blank=True, default='Energetika uchun yechimlar', max_length=120, verbose_name='Hero badge (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_tagline_en',
            field=models.CharField(blank=True, default='JOINT STOCK COMPANY', max_length=200, verbose_name='Tagline (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_tagline_ru',
            field=models.CharField(blank=True, default='АКЦИОНЕРНОЕ ОБЩЕСТВО', max_length=200, verbose_name='Tagline (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, default='Reliable partner for energy equipment supply in Uzbekistan', verbose_name='Footer text (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.TextField(blank=True, default='Надёжный партнёр по поставке энергетического оборудования в Узбекистане', verbose_name='Footer matni (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_uz',
            field=models.TextField(blank=True, default="O'zbekistonda energetika uskunalarini yetkazib berish bo'yicha ishonchli hamkor", verbose_name='Footer matni (UZ)'),
        ),
    ]
