# Generated by Django 4.2.30 on 2026-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_admin_brand_footer_hero_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#0e7c9b', help_text='Ikkinchi darajali rang (hex)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_section_color',
            field=models.CharField(default='#e6edf5', help_text="Bo'lim foni (alternativ, hex)", max_length=7, verbose_name="Bo'lim foni"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='rgba(26,36,51,0.09)', help_text='Chegara rangi — rgba yoki hex (masalan: rgba(0,0,0,0.1))', max_length=40, verbose_name='Chegara rangi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#d4890f', help_text='Asosiy brand rangi (hex)', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#1a2433', help_text='Asosiy matn rangi (hex)', max_length=7, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_secondary_color',
            field=models.CharField(default='#4b5c70', help_text='Ikkinchi darajali matn rangi (hex)', max_length=7, verbose_name='Secondary Text Color'),
        ),
    ]
