# Generated by Django 6.0.7 on 2026-07-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_update_default_theme_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='clients_count',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='projects_count',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='years_experience',
        ),
    ]
