# Generated by Django 6.0.7 on 2026-07-23 04:11

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_aboutsection_clients_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatedocument',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Matn (EN)'),
        ),
        migrations.AddField(
            model_name='corporatedocument',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Matn (RU)'),
        ),
        migrations.AddField(
            model_name='corporatedocument',
            name='content_uz',
            field=models.TextField(blank=True, verbose_name='Matn (UZ)'),
        ),
        migrations.AddField(
            model_name='corporatedocument',
            name='is_detailed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Batafsil maqola (detail sahifa)'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_detailed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Batafsil maqola (detail sahifa)'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='corporatecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='corporatecategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='corporate_docs/', verbose_name='Fayl (PDF/DOC)'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arxivda'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='published_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='corporatedocument',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=main.models.CorporateDocument.current_year, verbose_name='Yil (0 = Arxiv)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.CreateModel(
            name='CorporateDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='corporate_docs/files/', verbose_name='Fayl')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Fayl nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Fayl nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Fayl nomi (EN)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.corporatedocument')),
            ],
            options={
                'verbose_name': "Qo'shimcha fayl",
                'verbose_name_plural': "Qo'shimcha fayllar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorporateDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='corporate_docs/gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.corporatedocument')),
            ],
            options={
                'verbose_name': 'Hujjat rasmi',
                'verbose_name_plural': 'Hujjat rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/files/', verbose_name='Fayl')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Fayl nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Fayl nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Fayl nomi (EN)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.news')),
            ],
            options={
                'verbose_name': 'Yangilik fayli',
                'verbose_name_plural': 'Yangilik fayllari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
